name: deploy web on github-page
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
      - uses: actions/checkout@v4
      - name: Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.x
      - run: flutter config --enable-web
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub upgrade
      - run: flutter build web --release --web-renderer html --base-href /camera_front/
      - run: |
          cd build/web
          git init
          git config --global user.email adonin-2004@mail.com
          git config --global user.name AntonAdonin
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/AntonAdonin/camera_front.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
